version: '2'
services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "libaigo"
      LDAP_DOMAIN: "libaigo.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"
    ports:
      - "389:389"
      - "636:636"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "172.18.160.25"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "18080:80"
    depends_on:
      - openldap